// VUE/seriesvue/src/components/Menu.vue
<template>
  <nav
    class="navbar navbar-expand-md navbar-dark bg-dark"
    aria-label="Fourth navbar example"
  >
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Menu</a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarsExample04"
        aria-controls="navbarsExample04"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample04">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <router-link to="/home" class="nav-link">Home</router-link>
          </li>

          <li class="nav-item">
            <router-link to="/nuevopj" class="nav-link">Nuevo Personaje</router-link>
          </li>

          <li class="nav-item">
            <router-link to="/modificarpj" class="nav-link">Modificar Personaje</router-link>
          </li>

          <li class="nav-item">
            <router-link to="/home" class="nav-link">Modificar personaje</router-link>
          </li>

          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              id="dropdown04"
              data-bs-toggle="dropdown"
              aria-expanded="false"
              >Series</a
            >
            <ul class="dropdown-menu" aria-labelledby="dropdown04">
              <li v-for="(serie, index) in series" :key="index">
                <router-link :to="'/serie/' + serie.idSerie">{{
                  serie.nombre
                }}</router-link>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</template>

<script>
import SeriesService from "./../services/SeriesService";

const service = new SeriesService();
export default {
  name: "Menu",
  data() {
    return {
      series: [],
    };
  },
  mounted() {
    this.cargarSeries();
  },
  methods: {
    cargarSeries() {
      service.cargarSeries().then((result) => {
        this.series = result;
        console.log(result);
      });
    },
  },
};
</script>

// ANGULAR/practicaseries/src/app/components/menu/menu.component.ts
import { Component, OnInit } from '@angular/core';
import { Serie } from 'src/app/Models/Serie';
import { SerieService } from 'src/app/services/serie.service';


@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.css']
})
export class MenuComponent implements OnInit {
  public series!:Array<Serie>
  constructor(private _service: SerieService) { }

  cargarSeries():void{
    this._service.getSeries().subscribe(response=>{
      this.series=response;
    })
  }

  ngOnInit(): void {
    this.cargarSeries();
  }

}

<nav class="navbar navbar-expand-md navbar-dark bg-dark" aria-label="Fourth navbar example">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Menu</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample04"
            aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample04">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link item" [routerLink]="['/home']">Home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link item" [routerLink]="['/nuevopj']">Nuevo Personaje</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link item" [routerLink]="['/modificarpj']">Modificar Personaje</a>
                </li>
                

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-bs-toggle="dropdown"
                        aria-expanded="false">Series</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown04">
                        <a [routerLink]="['/detalles/',serie.idSerie]" *ngFor="let serie of series" class="dropdown-item">{{serie.nombre}}</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>
