// VUE/examenvueamh/src/components/Peliculas.vue
<template>
  <div>
    <div v-if="peliculas">
      <div
        class="card mb-5"
        style="width: 18rem; display: table; margin: 0 auto"
        v-for="(pelicula, index) in peliculas"
        :key="index"
      >
        <img class="card-img-top" :src="pelicula.foto" alt="Card image cap" />
        <div class="card-body">
          <h5 class="card-title">{{ pelicula.titulo }}</h5>
          <p class="card-text">{{ pelicula.argumento }}</p>
          <!-- <app-detallepeliculas
          [pelicula]="pelicula"
          [index]="i"
          (seleccionarDetallePadre)="seleccionarDetallePadre($event)"
        >
        </app-detallepeliculas> -->
        </div>
      </div>
    </div>

    <div v-else>
      <h1 class="text-danger">Loading...</h1>
    </div>
  </div>
</template>

<script>
import PeliculasService from "./../services/PeliculasService";
const service = new PeliculasService();

export default {
  name: "Peliculas",
  data() {
    return {
      peliculas: null,
      idgenero: 0,
      idnacionalidad: 0,
      titulo: "",
    };
  },
  methods: {
    getPeliculaGenero(idgenero) {
      service.getPeliculaGenero(idgenero).then((result) => {
        this.peliculas = result;
        console.log(this.peliculas);
      });
    },

    getPeliculaNacionalidad(idnacionalidad) {
      service.getPeliculaNacionalidad(idnacionalidad).then((result) => {
        this.peliculas = result;
      });
    },
  },
  mounted() {
    if (this.$route.params.genero) {
      this.idgenero = this.$route.params.genero;
      this.getPeliculaGenero(this.idgenero);
    } else if (this.$route.params.nacionalidad) {
      this.idnacionalidad = this.$route.params.nacionalidad;
      this.getPeliculaNacionalidad(this.idnacionalidad);
    }
  },
  watch: {
    "$route.params.genero"(nextVal, prevVal) {
      if (nextVal != prevVal) {
        this.idgenero = this.$route.params.genero;
        this.getPeliculaGenero(this.idgenero);
      }
    },
    "$route.params.nacionalidad"(nextVal, prevVal) {
      if (nextVal != prevVal) {
        this.idnacionalidad = this.$route.params.nacionalidad;
        this.getPeliculaNacionalidad(this.nacionalidad);
      }
    },
  },
};
</script>

<style>
</style>

// ANGULAR/examenangularamh/src/app/components/peliculas/peliculas.component.ts
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { ActivatedRoute, Params, Router } from '@angular/router';
import { Pelicula } from 'src/app/Models/Pelicula';
import { PeliculasserviceService } from 'src/app/services/peliculasservice.service';

@Component({
  selector: 'app-peliculas',
  templateUrl: './peliculas.component.html',
  styleUrls: ['./peliculas.component.css']
})
export class PeliculasComponent implements OnInit {
  public visible!: boolean
  public peliculas!: Array<Pelicula>
  public detalle!: Pelicula
  public detalles!: Array<any>
  public genero!: string
  public nacionalidad!: string

  constructor(private _service: PeliculasserviceService, private _router: Router, private _activeRoute: ActivatedRoute) { }

  seleccionarDetallePadre(event: Pelicula) {
    this.visible = true
    this.detalle = event
  }


  getPeliculaGenero(idgenero: number): void {
    this.visible = false
    this._service.getPeliculaGenero(idgenero).subscribe(response => {
      this.peliculas = response;
    })
  }

  getPeliculaNacionalidad(idnacionalidad: number): void {
    this.visible = false
    this._service.getPeliculaNacionalidad(idnacionalidad).subscribe(response => {
      this.peliculas = response;
    })
  }

  buscarPelicula(titulo: string): void {
    this._service.buscarPelicula(titulo).subscribe(response => {
      this.peliculas = response
    })
  }

  ngOnInit(): void {
    this._activeRoute.params.subscribe((params: Params) => {
      if (params['genero']) {
        this.getPeliculaGenero(params['genero']);
      }
      else if ((params['nacionalidad'])) {
        console.log("nacionalidad")
        this.getPeliculaNacionalidad(params['nacionalidad']);
      }
      else if (params['titulo']) {
        console.log(params['titulo'])
        this.buscarPelicula(params['titulo'])
      }


    });
  }

}

<h1>Peliculas</h1>

<div class="text-center" *ngIf="visible" id="detalles">
    <h2 style="color: goldenrod;">{{detalle.titulo}}</h2>
    <img src={{detalle.foto}} alt="" style="width: 300px; height: 400px;">
    <h2><i>{{detalle.argumento}}</i></h2>
    <h2>{{genero}}</h2>
    <h2>{{nacionalidad}}</h2>
</div>
<div *ngIf="!detalle">
    <h1 class="text-danger">Loading...</h1>
</div>
<hr>

<div *ngIf="!peliculas">
    <h1 class="text-danger">Loading...</h1>
</div>

<div *ngIf="peliculas" class="text-center">
    <div class="card mb-5" style="width: 18rem;display: table;margin: 0 auto;"
        *ngFor="let pelicula of peliculas;let i=index">
        <img class="card-img-top" src="{{pelicula.foto}}" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">{{pelicula.titulo}}</h5>
            <p class="card-text">{{pelicula.argumento}}</p>
            <app-detallepeliculas [pelicula]="pelicula" [index]="i"
                (seleccionarDetallePadre)="seleccionarDetallePadre($event)">
            </app-detallepeliculas>
        </div>
    </div>
</div>
