// VUE/apuestasvue/src/components/ListaApuestas.vue
<template>
  <div class="container text-center">

      <h1>Apuestas</h1>

        <div class="text-center" v-if=" apuestas">
            <router-link :to="'/realizarapuesta'" class="btn btn-danger mb-4">Realizar apuesta</router-link>
            <h1 class="text-danger">Local: Real Madrid, Visitante: Atletico de Madrid</h1>
            <table class=" table table-bordered table-info" style="display: table;width: 50rem;margin: 0 auto;">
                <thead>
                    <tr>
                        <th>Usuario</th>
                        <th>Resultado</th>
                        <th>Fecha</th>
                        <th>Eliminar</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="(apuesta, index) in apuestas" :key="index">
                        <td>{{apuesta.usuario}}</td>
                        <td>{{apuesta.resultado}}</td>
                        <td>{{apuesta.fecha}}</td>
                        <td><button class="btn btn-danger" @click="borrarApuesta(apuesta.idApuesta)">Borrar Apuesta</button></td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div v-else>
            <h1 class="text-danger">Loading...</h1>
        </div>

  </div>
</template>

<script>
import ChampionsService from "./../services/ChampionsService";
const service = new ChampionsService();
import Swal from 'sweetalert2'
export default {
name:"ListaApuestas",
data(){
    return{
        id:"",
        apuestas:null
    };
},
methods:{
    cargarApuestas(){
        service.cargarApuestas().then((result) => {
        this.apuestas = result;
      });
    },

    borrarApuesta(id){
        Swal.fire({
        title: 'Seguro?',
        text: "No podras deshacer esto!",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Dale!'
        }).then((result) => {
        if (result.isConfirmed) {  
        service.borrarApuesta(id).then((result) => {
        this.cargarApuestas()
        console.log(result)
        
        });
        
        Swal.fire(
        'Borrado!',
        'Apuesta borrada.',
        'success'
        )
        
        
    }
    
})
    
    }
},
mounted(){
    this.cargarApuestas()
},

}
</script>

<style>

</style>

// ANGULAR/apuestas/src/app/components/listaapuestas/listaapuestas.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Apuesta } from 'src/app/Models/Apuesta';
import { ApuestasService } from 'src/app/services/apuestas.service';


@Component({
  selector: 'app-listaapuestas',
  templateUrl: './listaapuestas.component.html',
  styleUrls: ['./listaapuestas.component.css']
})
export class ListaapuestasComponent implements OnInit {
  public apuestas!: Array<Apuesta>
  constructor(private _activeRoute: ActivatedRoute, private _service: ApuestasService) { }

  getApuestas(): void {
    this._service.getApuestas().subscribe(response => {
      this.apuestas = response;
    })
  }

  ngOnInit(): void {
    this.getApuestas()
  }

}

<h1>Apuestas</h1>

<div *ngIf="!apuestas">
    <h1 class="text-danger">Loading...</h1>
</div>

<div class="text-center" *ngIf=" apuestas">
    <a [routerLink]="['/realizarapuesta']" class="btn btn-danger mb-4">Realizar apuesta</a>
    <h1 class="text-danger">Local: Real Madrid, Visitante: Atletico de Madrid</h1>
    <table class=" table table-bordered table-info" style="display: table;width: 50rem;margin: 0 auto;">
        <thead>
            <tr>
                <th>Usuario</th>
                <th>Resultado</th>
                <th>Fecha</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let apuesta of apuestas">
                <td>{{apuesta.usuario}}</td>
                <td>{{apuesta.resultado}}</td>
                <td>{{apuesta.fecha}}</td>
            </tr>
        </tbody>
    </table>
</div>
