// VUE/apuestasvue/src/components/Busqueda.vue
<template>
  <div class="text-center mt-5" >
    <table class="table table-bordered" style="display: table;width: 50rem;margin: 0 auto;">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Imagen</th>
            </tr>
        </thead>
        <tbody>
            <tr v-for="(jugador, index) in jugadores" :key="index">
                <td>{{jugador.nombre}}</td>
                <td><img :src=jugador.imagen alt=""></td>
                
            </tr>
        </tbody>
    </table>
</div>
</template>

<script>
import ChampionsService from "./../services/ChampionsService";
const service = new ChampionsService();

export default {
name:"Busqueda",
data(){
    return{
        nombre:"",
        jugadores:[]
    };
},
mounted(){
    this.cargarJugadores()
},
methods:{
    cargarJugadores(){
      var nombre=this.$route.params.nombre
      service.buscarJugador(nombre).then((result) => {
        this.jugadores = result;
      });
    },
},
watch: {
    "$route.params.nombre"(nextVal, prevVal) {
      if (nextVal != prevVal) {
        this.nombre = this.$route.params.nombre;
        this.cargarJugadores();
      }
    },
  },
}

</script>

<style>

</style>

// ANGULAR/apuestas/src/app/components/busqueda/busqueda.component.ts
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { ActivatedRoute, Params } from '@angular/router';
import { Jugador } from 'src/app/Models/Jugador';
import { ApuestasService } from 'src/app/services/apuestas.service';


@Component({
  selector: 'app-busqueda',
  templateUrl: './busqueda.component.html',
  styleUrls: ['./busqueda.component.css']
})
export class BusquedaComponent implements OnInit {
  public jugadores!:Array<Jugador>
  @ViewChild("nombre") nombre!: ElementRef

  constructor(private _activeRoute: ActivatedRoute, private _service: ApuestasService) { }

  ngOnInit(): void {
    this._activeRoute.params.subscribe((params: Params) => {
      this._service.buscarJugador(params['nombre']).subscribe(response => {
        this.jugadores = response;
      })
    });
  }

}

<h1>Buscar jugadores</h1>

<div class="text-center mt-5" *ngIf="jugadores">
    <table class="table table-bordered" style="display: table;width: 50rem;margin: 0 auto;">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Imagen</th>
                <th>Detalles</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let jugador of jugadores">
                <td>{{jugador.nombre}}</td>
                <td><img src="{{jugador.imagen}}" alt=""></td>
                <td><a [routerLink]="['/detallesjugador/',jugador.idJugador]" class="btn btn-danger">Detalles</a></td>
            </tr>
        </tbody>
    </table>
</div>

<!--  -->
