// ANGULAR/serviciosangular/src/app/components/comic/comic.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { Comic } from 'src/app/Models/comic';

@Component({
  selector: 'app-comic',
  templateUrl: './comic.component.html',
  styleUrls: ['./comic.component.css']
})
export class ComicComponent implements OnInit {
  @Input() comic!: Comic;
  @Input() index!: number;
  @Output() seleccionarFavorito: EventEmitter<any> = new EventEmitter();
  @Output() eliminarComic: EventEmitter<any> = new EventEmitter();
  @Output() modificarComic: EventEmitter<any> = new EventEmitter();

  seleccionarFavoritoHijo(): void {
    this.seleccionarFavorito.emit(this.comic)
  }

  eliminarComicHijo(): void {
    this.eliminarComic.emit(this.index)
  }

  modificarComicHijo(): void {
    this.modificarComic.emit(this.index)
  }

  constructor() { }

  ngOnInit(): void {
  }

}

<div>
    <h2 style="color: blueviolet;">{{comic.nombre}}</h2>
    <img src={{comic.imagen}} alt="" style="width: 300px; height: 400px;">
    <h2><i>{{comic.descripcion}}</i></h2>
    <button style="background-color: goldenrod;" (click)="seleccionarFavoritoHijo()">Favorito</button>

    <button (click)="modificarComicHijo()" style="background-color: dodgerblue;">Modificar Comic</button>

    <button (click)="eliminarComicHijo()" style="background-color: firebrick;">Eliminar comic</button>
    <hr>
</div>

// REACT/reactclases/src/Components/Comics/Comic.js
import { Component } from "react";

class Comic extends Component {

    render() {
        return (<div style={{
            backgroundColor : "#758090"
            , color : "#4ECDC4"
        }}>
            <h1>
                {this.props.Comic.titulo}                
            </h1>
            <h6>{this.props.Comic.descripcion}</h6>
            <img src={this.props.Comic.imagen} />
            <br/>
            <button onClick={ () => {
                this.props.SeleccionarFavorito(this.props.Comic)
            }}>
                Seleccionar favorito
            </button>
            <button onClick={ () => {
                this.props.EliminarComic(this.props.Index)
            }}> 
                Eliminar comic
            </button>
            <button onClick={() => {
                var index = this.props.Index;
                this.props.modificarComic(index);
            }} style={{backgroundColor:"blue", color:"white"}}>
                Modificar Comic
            </button>

        </div>)
    }
}

export default Comic;
