// VUE/serviciosvue/src/components/Departamentos/DetallesDepartamento.vue
<template>
  <div class="container text-center">
    <h1>Detalles</h1>
    <router-link class="btn btn-info" to="/departamentos"
      >Volver al listado</router-link
    >
    <h2 class="text-primary">
      {{ departamento.nombre + ", " + departamento.localidad }}
    </h2>
  </div>
</template>

<script>
export default {
  name: "DetallesDepartamento",
  mounted() {
    this.departamento.numero = this.$route.params.iddepartamento;
    this.departamento.nombre = this.$route.params.nombre;
    this.departamento.localidad = this.$route.params.localidad;
  },
  data() {
    return {
      departamento: {
        numero: 0,
        nombre: "",
        localidad: "",
      },
    };
  },
};
</script>

<style>
</style>

// REACT/reactservicios/src/Components/Departamentos/DetallesDepartamento.js
import React, { Component } from 'react'
import { NavLink } from 'react-router-dom'

export default class DetallesDepartamento extends Component {
    render() {
        return (
            <div>
                <h1>Detalles Departamento</h1>
                <h2 >Numero: {this.props.iddepartamento}</h2>
                <h2 >Nombre: {this.props.nombre}</h2>
                <h2 >Localidad: {this.props.localidad}</h2>
                <NavLink to={"/departamentos"} className="btn btn-success">Volver al listado</NavLink>
                <NavLink to={"/updatedepartamento/"+this.props.iddepartamento} className="btn btn-info">Modificar</NavLink>
            </div>
        )
    }
}
