// VUE/serviciosvue/src/components/Departamentos/InsertarDepartamento.vue
<template>
  <div class="container text-center">
    <h1>Insertar departamento</h1>

    <router-link to="/departamentos" class="btn btn-primary"
      >Volver al listado</router-link
    >
    <div style="width: 500px; margin: 0 auto">
      <form method="post" v-on:submit.prevent="insertarDepartamento()">
        <div class="form-group">
          <label>Numero</label>
          <input
            type="number"
            class="form-control"
            v-model="departamento.numero"
          />
        </div>
        <div class="form-group">
          <label>Nombre</label>
          <input
            type="text"
            class="form-control"
            v-model="departamento.nombre"
          />
        </div>
        <div class="form-group">
          <label>Localidad</label>
          <input
            type="text"
            class="form-control"
            v-model="departamento.localidad"
          />
        </div>
        <button class="btn btn-success mt-4">Insertar Departamento</button>
      </form>
    </div>
  </div>
</template>

<script>
import ServiceDepartamentos from "./../../services/ServiceDepartamentos";

const service = new ServiceDepartamentos();
export default {
  name: "InsertarDepartamento",
  data() {
    return {
      departamento: {
        numero: 0,
        nombre: "",
        localidad: "",
      },
    };
  },
  methods: {
    insertarDepartamento() {
      this.departamento.numero = parseInt(this.departamento.numero);
      service.postDepartamento(this.departamento).then((result) => {
        console.log(result);
        this.$router.push("/departamentos");
      });
    },
  },
};
</script>

<style>
</style>

// REACT/reactservicios/src/Components/Departamentos/InsertarDepartamento.js
import axios from 'axios';
import React, { Component } from 'react'
import { Redirect } from 'react-router';
import Global from '../../Global';


export default class InsertarDepartamento extends Component {

    cajaNumeroRef=React.createRef();
    cajaNombreRef=React.createRef();
    cajaLocalidadRef=React.createRef();

    state={
        mensaje: "",
        status: false
    }

    insertarDepartamento=(e)=>{
        e.preventDefault();
        var num=parseInt(this.cajaNumeroRef.current.value);
        var nom=this.cajaNombreRef.current.value;
        var loc=this.cajaLocalidadRef.current.value;

        var departamento={
            numero: num,
            nombre: nom,
            localidad:loc
        }

        var request="/webresources/departamentos/post";
        var url=Global.urldepartamentosCRUD+request;
        axios.post(url, departamento).then(res=>{
            this.setState({
                mensaje:"Departamento insertado con exito",
                status:true
            })
        });
    }

    render() {
        if(this.state.status==true){
                return(
                    
                    <Redirect to="/departamentos"></Redirect>
                );
        }
        return (
            
            <div>
                <h1>Nuevo Departamento</h1>
                <form style={{width:"500px", display:"table", margin:"0 auto"}} onSubmit={this.insertarDepartamento}>
                    <div className="form-group row">
                        <label>Numero</label>
                        <input type="number" className="form-control" ref={this.cajaNumeroRef} required></input >
                    </div>
                    <div className="form-group row">
                    <label>Nombre</label>
                        <input type="text" className="form-control" ref={this.cajaNombreRef} required></input>
                    </div>
                    <div className="form-group row">
                    <label>Localidad</label>
                        <input type="text" className="form-control" ref={this.cajaLocalidadRef} required></input>
                    </div>
                    <br/>
                    <button className="btn btn-info">Insertar Departamento</button>
                </form>
                <h2 style={{color:"red"}}>{this.state.mensaje}</h2>
            </div>
        )
    }
}
