// VUE/proyectovuefinal/src/components/Routing/Deporte.vue
<template>
  <div>
    <h1>{{ deporte }}</h1>
    <button @click="seleccionarFavorito(deporte)">Seleccionar Favorito</button>
  </div>
</template>

<script>
export default {
  name: "Deporte",
  props: ["deporte"],

  methods: {
    seleccionarFavorito(depor) {
      this.$emit("seleccionarFavoritoParent", depor);
    },
  },
};
</script>

// REACT/reactclases/src/Components/Deportes/Deporte.js
import React, {Component} from 'react';

class Deporte extends Component{

    seleccionarFavorito=()=>{
        var deporte=this.props.nombre;
        this.props.mostrarFav(deporte);
    };

render(){
    return(<React.Fragment>
            <li style={{color:"blue"}}>
                {this.props.nombre}
                <button onClick={()=>this.seleccionarFavorito()}>
                    Seleccionar favorito
                </button>
            </li>

    </React.Fragment>
    )
    }
}

export default Deporte;
