// REACT/reactclases/src/Components/Comics/Comic.js
import { Component } from "react";

class Comic extends Component {

    render() {
        return (<div style={{
            backgroundColor : "#758090"
            , color : "#4ECDC4"
        }}>
            <h1>
                {this.props.Comic.titulo}                
            </h1>
            <h6>{this.props.Comic.descripcion}</h6>
            <img src={this.props.Comic.imagen} />
            <br/>
            <button onClick={ () => {
                this.props.SeleccionarFavorito(this.props.Comic)
            }}>
                Seleccionar favorito
            </button>
            <button onClick={ () => {
                this.props.EliminarComic(this.props.Index)
            }}> 
                Eliminar comic
            </button>
            <button onClick={() => {
                var index = this.props.Index;
                this.props.modificarComic(index);
            }} style={{backgroundColor:"blue", color:"white"}}>
                Modificar Comic
            </button>

        </div>)
    }
}

export default Comic;

// VUE/proyectovuefinal/src/components/Routing/Comic.vue
<template>
  <div class="container">
    <h1 class="text-danger">{{ comic.titulo }}</h1>
    <img :src="comic.imagen" />
    <h2 class="text-primary">{{ comic.descripcion }}</h2>
    <!-- :class="{
      rojo: comic.year<=2000,
      verde: comic.year>2000
      }" -->
    <button class="btn btn-info" @click="seleccionarFavorito(comic)">
      Seleccionar Favorito
    </button>
    <button class="btn btn-success" @click="modificarComic(comicindex)">
      Modificar comic
    </button>
    <button class="btn btn-danger" @click="eliminarComic(comicindex)">
      Eliminar comic
    </button>
    <hr />
  </div>
</template>

<script>
export default {
  name: "Comic",
  props: ["comic", "comicindex"],
  methods: {
    seleccionarFavorito(comic) {
      this.$emit("seleccionarFavoritoParent", comic);
    },
    eliminarComic(comicindex) {
      this.$emit("eliminarComicParent", comicindex);
    },
    modificarComic(comicindex) {
      this.$emit("modificarComicParent", comicindex);
    },
  },
};
</script>

<style scoped>
@import "./../../assets/app.css";
</style>
