// REACT/reactclases/src/Components/Numeros/Numeros.js
import React, {Component} from 'react';
import Numero from './Numero';

var resultado=0;
class Numeros extends Component{

    state={
        numeros:[4,5],
        suma:0
    };

    
    sumar=(numero)=>{
        resultado+=numero;
        this.setState({
            suma:resultado
        })
    }

    nuevoNumero=()=>{
        var random=Math.floor(Math.random() * 10)+1;
        this.state.numeros.push(random);
        this.setState({
            numeros:this.state.numeros
        });
    }

    render(){
        return(
            <React.Fragment>
                <h1>La suma es: <span style={{color:"red"}}>{this.state.suma}</span></h1>

                <button onClick={()=>this.nuevoNumero()}>
                    Añade un nuevo numero
                </button>

                {this.state.numeros.map((num,index)=>{
                    return (<Numero numero={num} key={index} sumarNumeros={this.sumar}/>);
                })}


            </React.Fragment>
            
        );
    }
}

export default Numeros;

// VUE/proyectovuefinal/src/components/Routing/Numeros.vue
<template>
  <div>
    <h1>Numeros Padre</h1>
    <h2 class="text-danger">La suma es {{ resultado }}</h2>
    <button class="btn btn-primary" @click="crearNumeros()">
      Nuevo numero
    </button>
    <hr />
    <div v-for="(n, index) in numeros" :key="index">
      <Numero :valor="n" v-on:sumarParent="sumarParent" />
    </div>
  </div>
</template>

<script>
import Numero from "./Numero.vue";
export default {
  name: "Numeros",
  data() {
    return {
      numeros: [],
      resultado: 0,
    };
  },
  components: {
    Numero,
  },
  methods: {
    crearNumeros() {
      var num = Math.floor(Math.random() * 10) + 1;
      this.numeros.push(num);
    },
    sumarParent(valor) {
      this.resultado += valor;
    },
  },
};
</script>
