// VUE/seriesvue/src/components/Personajes.vue
<template>
  <div>
      <h1>Personajes</h1>
      <router-link class="btn btn-danger" :to="'/serie/' + this.id">Volver</router-link>
      <table class="table table-bordered">
          <thead>
              <tr>
                  <th>Personaje</th>
                  <th>Imagen</th>
              </tr>
          </thead>
          <tbody>
              <tr v-for="(personaje, index) in personajes" :key="index">
                  <td>{{personaje.nombre}}</td>
                  <td><img style="width:420px;height:300px" :src="personaje.imagen" alt="Card image cap" /></td>
              </tr>
          </tbody>
      </table>
  </div>
</template>

<script>
import SeriesService from "./../services/SeriesService";

const service = new SeriesService();
export default {
    name:"Personajes",
    mounted() {
    this.id = this.$route.params.idserie;
    this.cargarPersonajes();
    console.log(this.personajes)
  },
    data(){
        return{
            id:0,
            personajes:[]
        };
    },
    methods:{
    cargarPersonajes() {
      service.personajesSerie(this.id).then((result) => {
        this.personajes = result;
        console.log(result);
      });
    },
    },
}
</script>

<style>
</style>

// REACT/examenreactamh/src/components/series/Personajes.js
import axios from 'axios'
import React, { Component } from 'react'
import { NavLink } from 'react-router-dom'
import Global from '../../Global'

export default class Personajes extends Component {

    state={
        personajes:[],
        status:true
    }

    cargarPersonajes=()=>{
        var request="/api/Series/PersonajesSerie/"+this.props.id
        var url=Global.urlseries+request;
        axios.get(url).then(res=>{
            this.setState({
                personajes:res.data
            })
        })
        
    }

    componentDidMount=()=>{
        this.cargarPersonajes();
    }
    render() {
        return (
            <div>
                <NavLink className="btn btn-danger" to={"/infoseries/"+this.props.id+"/"+this.props.nombre}>
                Volver
                </NavLink>
                 <table className="table table-bordered">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Imagen</th>
                        </tr>
                    </thead>
                    <tbody>
                        {this.state.personajes.map((p,index)=>{
                    return(
                        <tr key={index}>
                            <td>{p.nombre}</td>
                            <td><img src={p.imagen} style={{width:"200px", height:"150px"}}/></td>
                        </tr>
                    )
                })}
                    </tbody>
                </table>
            </div>
        )
    }
}
