// VUE/apuestasvue/src/components/Menu.vue
<template>
  <nav
    class="navbar navbar-expand-md navbar-dark bg-dark"
    aria-label="Fourth navbar example"
  >
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Menu</a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarsExample04"
        aria-controls="navbarsExample04"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample04">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <router-link to="/home" class="nav-link">Home</router-link>
          </li>

          <li class="nav-item">
            <router-link to="/listaapuestas" class="nav-link">Apuestas</router-link>
          </li>

          

          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              id="dropdown04"
              data-bs-toggle="dropdown"
              aria-expanded="false"
              >Equipos</a
            >
            <ul class="dropdown-menu" aria-labelledby="dropdown04">
              <li v-for="(equipo, index) in equipos" :key="index">
                <router-link :to="'/detallesequipo/' + equipo.idEquipo">{{
                  equipo.nombre
                }}</router-link>
              </li>
            </ul>
          </li>

          <form method="post" v-on:submit.prevent="buscarJugador"  class="form-inline my-2 my-md-0 input-group" >
                <input class="form-control" type="text" placeholder="Buscar" v-model="nombre" >
                <button class="btn btn-outline-info" style="float: right;">Buscar</button>
          </form>
          
        </ul>
      </div>
    </div>
  </nav>
</template>

<script>
import ChampionsService from "./../services/ChampionsService";
const service = new ChampionsService();

export default {
  name: "Menu",
  data(){
      return{
        nombre:"",
        equipos:[]
      };
  },
  methods:{
      buscarJugador(){
        this.$router.push('/busqueda/'+this.nombre)
      },

      cargarEquipos(){
        service.cargarEquipos().then((result) => {
        this.equipos = result;
      });
      },
  },
  mounted(){
    this.cargarEquipos()
  }
  
  
};
</script>

// ANGULAR/apuestas/src/app/components/menu/menu.component.ts
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Equipo } from 'src/app/Models/Equipo';
import { ApuestasService } from 'src/app/services/apuestas.service';

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.css']
})
export class MenuComponent implements OnInit {
  public equipos!: Array<Equipo>
  @ViewChild("nombre") nombre!: ElementRef

  constructor(private _service: ApuestasService,private _router: Router) { }

  getEquipos(): void {
    this._service.getEquipos().subscribe(response => {
      this.equipos = response;
    })
  }

  buscarJugador():void{
    var nombre=this.nombre.nativeElement.value;
    this._router.navigate(["/busqueda/"+nombre]);
  }


  ngOnInit(): void {
    this.getEquipos();
  }

}

<nav class="navbar navbar-expand-md navbar-dark bg-dark" aria-label="Fourth navbar example">
    <div class="container-fluid">
        <a class="navbar-brand" [routerLink]="['/home']">Champions</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample04"
            aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample04">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link item" [routerLink]="['/home']">Home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link item" [routerLink]="['/apuestas']">Apuestas</a>
                </li>


                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-bs-toggle="dropdown"
                        aria-expanded="false">Equipos</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown04">
                        <a class="dropdown-item" [routerLink]="['/detallesequipo/',equipo.idEquipo]"
                            *ngFor="let equipo of equipos">{{equipo.nombre}}</a>
                    </div>
                </li>
                <form #buscarForm="ngForm" class="form-inline my-2 my-md-0 input-group" >
                    <input class="form-control" type="text" placeholder="Buscar" name="nombre" #nombre>
                    <button class="btn btn-outline-info" style="float: right;" (click)="buscarJugador()">Buscar</button>
                </form>
            </ul>
        </div>
    </div>
</nav>
