// ANGULAR/apuestas/src/app/components/realizarapuesta/realizarapuesta.component.ts
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { Router } from '@angular/router';
import { Apuesta } from 'src/app/Models/Apuesta';
import { ApuestasService } from 'src/app/services/apuestas.service';


@Component({
  selector: 'app-realizarapuesta',
  templateUrl: './realizarapuesta.component.html',
  styleUrls: ['./realizarapuesta.component.css']
})
export class RealizarapuestaComponent implements OnInit {
  public apuesta!: Apuesta
  @ViewChild("cajanombre") cajanombre!: ElementRef
  @ViewChild("cajaRM") cajaRM!: ElementRef
  @ViewChild("cajaAM") cajaAM!: ElementRef
  @ViewChild("cajafecha") cajafecha!: ElementRef
  constructor(private _service: ApuestasService, private _router: Router) { }

  realizarApuesta() {
    var id = 0;
    var usuario = this.cajanombre.nativeElement.value;
    var resultado = this.cajaRM.nativeElement.value + "-" + this.cajaAM.nativeElement.value
    var fecha = this.cajafecha.nativeElement.value;
    var apuesta = new Apuesta(id, usuario, resultado, fecha)

    this._service.realizarApuesta(apuesta).subscribe(response => {
      this._router.navigate(["/apuestas"]);
    })
  }

  ngOnInit(): void {
  }

}

<h1>Realizar apuestas</h1>

<div class="text-center" style="display: table;width: 30rem;margin: 0 auto;">
    <form #realizarForm="ngForm">
        <label>Usuario: </label>
        <input class="form-control" type="text" name="cajanombre" #cajanombre>

        <label>Real Madrid: </label>
        <input class="form-control" type="number" name="cajaRM" #cajaRM>

        <label>Atletico de Madrid: </label>
        <input class="form-control" type="number" name="cajaAM" #cajaAM>

        <label>Fecha: </label>
        <input class="form-control" type="date" name="cajafecha" #cajafecha>

        <button (click)="realizarApuesta()" class="btn btn-primary mt-5">Apostar</button>
    </form>
</div>

// VUE/apuestasvue/src/components/RealizarApuesta.vue
<template>
  <div class="container text-center">
      <h1>Realizar apuestas</h1>

    <div class="text-center" style="display: table;width: 30rem;margin: 0 auto;">
        <form method="post" v-on:submit.prevent="realizarApuesta">
            <label>Usuario: </label>
            <input class="form-control" type="text" v-model="usuario">

            <label>Real Madrid: </label>
            <input class="form-control" type="number" v-model="rm">

            <label>Atletico de Madrid: </label>
            <input class="form-control" type="number" v-model="am">

            <label>Fecha: </label>
            <input class="form-control" type="date" v-model="fecha">

            <button class="btn btn-primary mt-5">Apostar</button>
        </form>
    </div>
  </div>
</template>

<script>
import ChampionsService from "./../services/ChampionsService";
const service = new ChampionsService();
export default {
name:"RealizarApuesta",
methods:{
    realizarApuesta(){
        var usuario=this.usuario;
        var resultado=this.rm+"-"+this.am;
        var fecha=this.fecha;
        var apuesta={
            idApuesta:0,
            usuario:usuario,
            resultado:resultado,
            fecha:fecha
        }
        service.realizarApuestas(apuesta).then(result => {
            console.log(result);
            this.$router.push("/listaapuestas")
            }); 
        
    },
},
data(){
    return{
        id:0,
        usuario:"",
        rm:"",
        am:"",
        fecha:""
    };
    
},
}
</script>

<style>

</style>
