// VUE/seriesvue/src/components/NuevoPersonaje.vue
<template>
  <div class="container">
      <h1>Nuevo personaje</h1>
      <form method="post" v-on:submit.prevent="insertarPersonaje">
          <label>Nombre: </label>
          <input class="form-control" type="text" v-model="nombre"/>

          <label>Imagen: </label>
          <input class="form-control" type="text" v-model="imagen"/>

          <label>Serie: </label>
          <select class="form-control" v-model="serie">
              <option v-for="(serie, index) in series" :key="index" :value="serie.idSerie">{{serie.nombre}}</option>
          </select>

          <button class="btn btn-success mt-4">Insertar personaje</button>

      </form>
  </div>
</template>

<script>
import SeriesService from "./../services/SeriesService";

const service = new SeriesService();
export default {
    name:"NuevoPersonaje",
    data(){
        return{
            nombre:"",
            imagen:"",
            serie:"",
            personaje:{},
            series:[]
        };
    },
    mounted(){
        this.cargarSeries();
    },
    methods:{
        cargarSeries(){
        service.cargarSeries().then((result) => {
        this.series = result;
        console.log(result);
      });
        },

        insertarPersonaje(){
            this.personaje={
               idPersonaje:0,
               nombre: this.nombre,
               imagen: this.imagen,
               idSerie: this.serie 
            };
            service.insertarPersonaje(this.personaje).then((result) => {
            console.log(result);
            });
            this.$router.push('/serie/'+this.serie)
        }
    },
}
</script>

<style>

</style>

// ANGULAR/practicaseries/src/app/components/nuevopersonaje/nuevopersonaje.component.ts
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { Router } from '@angular/router';
import { Personaje } from 'src/app/Models/Personaje';
import { Serie } from 'src/app/Models/Serie';
import { SerieService } from 'src/app/services/serie.service';

@Component({
  selector: 'app-nuevopersonaje',
  templateUrl: './nuevopersonaje.component.html',
  styleUrls: ['./nuevopersonaje.component.css']
})
export class NuevopersonajeComponent implements OnInit {
  public series!: Array<Serie>

  @ViewChild("cajanombre") cajanombre!: ElementRef;
  @ViewChild("cajaimagen") cajaimagen!: ElementRef;
  @ViewChild("cajaserie") cajaserie!: ElementRef;
  constructor(private _service: SerieService, private _router: Router) { }

  cargarSeries(): void {
    this._service.getSeries().subscribe(response => {
      this.series = response;
    })
  }

  insertarPersonaje(): void {
    var personaje: Personaje = {
      idPersonaje: 0,
      nombre: this.cajanombre.nativeElement.value,
      imagen: this.cajaimagen.nativeElement.value,
      idSerie: parseInt(this.cajaserie.nativeElement.value)
    }
    console.log(personaje)

    this._service.insertarPersonaje(personaje).subscribe(response => {
      this._router.navigate(["/personajes", personaje.idSerie]);
    })


  }

  ngOnInit(): void {
    this.cargarSeries();
  }

}

<h1>Nuevo personaje</h1>
<form #nuevoForm="ngForm" (ngSubmit)="insertarPersonaje()" style="display: table;margin: 0 auto;width: 70%;">
    <label>Nombre: </label>
    <input class="form-control" type="text" name="cajanombre" #cajanombre>

    <label>Imagen: </label>
    <input class="form-control" type="text" name="cajaimagen" #cajaimagen>

    <label>Serie: </label>
    <select class="form-control" name="cajaserie" #cajaserie>
        <option *ngFor="let serie of series" value="{{serie.idSerie}}">{{serie.nombre}}</option>
    </select>

    <button type="submit" class="btn btn-primary mt-4">Insertar personaje</button>
</form>
