// ANGULAR/serviciosangular/src/app/components/empleadosoficio/empleadosoficio.component.ts
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { Empleado2 } from 'src/app/Models/empleado2';
import { Empleado2Service } from 'src/app/services/empleado2.service';
Empleado2Service

@Component({
  selector: 'app-empleadosoficio',
  templateUrl: './empleadosoficio.component.html',
  styleUrls: ['./empleadosoficio.component.css']
})
export class EmpleadosoficioComponent implements OnInit {
  public oficios!: Array<string>
  public empleados!: Array<Empleado2>
  @ViewChild("cajaoficio") cajaoficio!: ElementRef;
  constructor(private _service: Empleado2Service) { }

  cargarOficios() {
    this._service.getOficios().subscribe(response => {
      this.oficios = response
    })
  }

  cargarEmpleados() {
    var oficio = this.cajaoficio.nativeElement.value
    this._service.getEmpleadosOficio(oficio).subscribe(response => {
      this.empleados = response
    })
  }

  ngOnInit(): void {
    this.cargarOficios()
  }

}

<h1>Empleados Oficios</h1>

<form #formOficios="ngForm">
    <label>Seleccione un oficio</label>
    <select class="form-control" name="cajaoficio" #cajaoficio>
        <option *ngFor="let oficio of oficios">{{oficio}}</option>
    </select>
    <button class="btn btn-outline-primary mt-3" (click)="cargarEmpleados()">Cargar tabla</button>
</form>

<table class="table table-bordered mt-4" *ngIf="empleados">
    <thead>
        <tr>
            <th>Id Empleado</th>
            <th>Apellido</th>
            <th>Oficio</th>
            <th>Salario</th>
            <th>Departamento</th>
        </tr>
    </thead>
    <tbody>
        <tr *ngFor="let emp of empleados">
            <td>{{emp.idEmpleado}}</td>
            <td>{{emp.apellido}}</td>
            <td>{{emp.oficio}}</td>
            <td>{{emp.salario}}</td>
            <td>{{emp.departamento}}</td>
        </tr>
    </tbody>
</table>

// VUE/serviciosvue/src/components/EmpleadosOficio.vue
<template>
  <div>
    <h1>Oficios</h1>
    <label>Seleccione un oficio</label>
    <form method="post">
      <select
        class="form-control"
        @change="cargarEmpleados"
        v-model="oficioselect"
      >
        <option v-for="(ofi, index) in oficios" :key="index" :value="ofi">
          {{ ofi }}
        </option>
      </select>
    </form>
    <table class="table table-bordered mt-3" v-if="oficioselect">
      <thead>
        <tr>
          <th>Apellido</th>
          <th>Salario</th>
          <th>Departamento</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(emp, index) in empleados" :key="index">
          <td>{{ emp.apellido }}</td>
          <td>{{ emp.salario }}</td>
          <td>{{ emp.departamento }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
import axios from "axios";
import { Global } from "./Global";
export default {
  name: "EmpleadosOficio",
  mounted() {
    this.cargarOficios();
  },
  methods: {
    cargarOficios() {
      var request = "api/Empleados/oficios";
      var url = Global.urlempleados + request;
      axios.get(url).then((res) => {
        this.oficios = res.data;
      });
    },
    cargarEmpleados() {
      var request = "api/Empleados/EmpleadosOficio/" + this.oficioselect;
      var url = Global.urlempleados + request;
      axios.get(url).then((res) => {
        this.empleados = res.data;
      });
    },
  },
  data() {
    return {
      oficios: [],
      empleados: [],
      oficioselect: null,
    };
  },
};
</script>
