// ANGULAR/practicaseries/src/app/components/modificarpersonaje/modificarpersonaje.component.ts
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { Router } from '@angular/router';
import { Personaje } from 'src/app/Models/Personaje';
import { Serie } from 'src/app/Models/Serie';
import { SerieService } from 'src/app/services/serie.service';

@Component({
  selector: 'app-modificarpersonaje',
  templateUrl: './modificarpersonaje.component.html',
  styleUrls: ['./modificarpersonaje.component.css']
})
export class ModificarpersonajeComponent implements OnInit {
  public series!: Array<Serie>
  public personajes!: Array<Personaje>

  @ViewChild("cajaserie") cajaserie!: ElementRef;
  @ViewChild("cajapersonaje") cajapersonaje!: ElementRef;

  constructor(private _service: SerieService, private _router: Router) { }
  cargarSeries(): void {
    this._service.getSeries().subscribe(response => {
      this.series = response;
    })
  }

  cargarPersonajes(): void {
    this._service.getPersonajes().subscribe(response => {
      this.personajes = response;
    })
  }

  modificarPersonaje() {
    var idserie = parseInt(this.cajaserie.nativeElement.value)
    var idpersonaje = parseInt(this.cajapersonaje.nativeElement.value)
    this._service.modificarPersonaje(idpersonaje, idserie).subscribe(response => {
      this._router.navigate(["/personajes", idserie]);
    })


  }

  ngOnInit(): void {
    this.cargarSeries();
    this.cargarPersonajes();
  }

}

<h1>Modificar personajes</h1>

<form #modForm="ngForm" (ngSubmit)="modificarPersonaje()" style="display: table;margin: 0 auto;width: 70%;">
    <label>Escoge una serie: </label>
    <select class="form-control" name="cajaserie" #cajaserie>
        <option *ngFor="let serie of series" value="{{serie.idSerie}}">{{serie.nombre}}</option>
    </select> 

    <label>Escoge un personaje: </label>
    <select class="form-control" name="cajapersonaje" #cajapersonaje>
        <option *ngFor="let pj of personajes" value="{{pj.idPersonaje}}">{{pj.nombre}}</option>
    </select>

    <button type="submit" class="btn btn-primary mt-4">Modificar personaje</button>
</form>

// VUE/seriesvue/src/components/ModificarPersonaje.vue
<template>
  <div class="container">
    <h1>Modificar personaje</h1>
    <form method="post" v-on:submit.prevent="modificarPersonaje">
        <label>Seleccione una serie: </label>
        <select class="form-control" v-model="serie">
            <option v-for="(serie, index) in series" :key="index" :value="serie.idSerie">{{serie.nombre}}</option>
        </select>

        <label>Seleccione un Personaje: </label>
        <select class="form-control" v-model="personaje">
            <option v-for="(pj, index) in personajes" :key="index" :value="pj.idPersonaje">{{pj.nombre}}</option>
        </select>

        <button class="btn btn-success mt-4">Modificar Personaje</button>
    </form>
  </div>
</template>

<script>
import SeriesService from "./../services/SeriesService";

const service = new SeriesService();
export default {
    name:"ModificarPersonaje",
    mounted(){
        this.cargarSeries();
        this.cargarPersonajes();
    },
    methods:{
        cargarSeries(){
        service.cargarSeries().then((result) => {
        this.series = result;
        console.log(result);
      });
        },

        cargarPersonajes(){
        service.cargarPersonajes().then((result) => {
        this.personajes = result;
        console.log(result);
      });
        },

        modificarPersonaje(){
        service.modificarPersonaje(this.personaje,this.serie).then((result) => {
        console.log(result);
      });
        this.$router.push('/serie/'+this.serie)
        }
    },
    data(){
        return{
            series:[],
            personajes:[],
            serie:0,
            personaje:0,
        };
    },
}
</script>

<style>

</style>
