// REACT/examenreactamh/src/components/series/NuevoPersonaje.js
import axios from 'axios'
import React, { Component } from 'react'
import Global from '../../Global'
import { NavLink } from 'react-router-dom';
import { Redirect } from 'react-router';

export default class NuevoPersonaje extends Component {
    cajaNombre=React.createRef();
    cajaImagen=React.createRef();
    cajaSerie=React.createRef();

    state={
        series:[],
        status:false,
        idSerie:0
    }

    cargarSeries=()=>{
        var request="/api/Series"
        var url=Global.urlseries+request;
        axios.get(url).then(res=>{
            this.setState({
                series:res.data,
            })
        })
    }

    crearPersonaje=(e)=>{
        e.preventDefault();
        var nombre=this.cajaNombre.current.value;
        var img=this.cajaImagen.current.value;
        var serie=parseInt(this.cajaSerie.current.value);
        

        var personaje={
            idPersonaje:0,
            nombre: nombre,
            imagen:img,
            idSerie:serie
        }

        var request="/api/Personajes";
        var url=Global.urlseries+request;
        axios.post(url,personaje).then(res=>{
            this.setState({
                status:true,
                idSerie:serie
            })
        })
    }

    componentDidMount=()=>{
        this.cargarSeries();
    }

    render() {
        if(this.state.status==true){
            return(
                <Redirect to={"/personajes/"+this.state.idSerie}></Redirect>
            )
        }
        return (
            <div>
            <h1>Nuevo Personaje</h1>
            <form style={{width:"500px", display:"table", margin:"0 auto"}} onSubmit={this.crearPersonaje}>

                <label>Nombre:</label>
                <input className="form-control" type="text" ref={this.cajaNombre} required></input>

                <label>Imagen: </label>
                <input className="form-control"  type="text" ref={this.cajaImagen} required></input>

                <label>Serie: </label>
                <select className="form-control" ref={this.cajaSerie}>

                {this.state.series.map((s,index)=>{
                    return(
                        <option value={s.idSerie} key={index}>{s.nombre}</option>
                    )
                })}

                </select>

                <br/>

                <button className="btn btn-info">Crear personaje</button>
            </form>
        </div>
        )
    }
}

// VUE/seriesvue/src/components/NuevoPersonaje.vue
<template>
  <div class="container">
      <h1>Nuevo personaje</h1>
      <form method="post" v-on:submit.prevent="insertarPersonaje">
          <label>Nombre: </label>
          <input class="form-control" type="text" v-model="nombre"/>

          <label>Imagen: </label>
          <input class="form-control" type="text" v-model="imagen"/>

          <label>Serie: </label>
          <select class="form-control" v-model="serie">
              <option v-for="(serie, index) in series" :key="index" :value="serie.idSerie">{{serie.nombre}}</option>
          </select>

          <button class="btn btn-success mt-4">Insertar personaje</button>

      </form>
  </div>
</template>

<script>
import SeriesService from "./../services/SeriesService";

const service = new SeriesService();
export default {
    name:"NuevoPersonaje",
    data(){
        return{
            nombre:"",
            imagen:"",
            serie:"",
            personaje:{},
            series:[]
        };
    },
    mounted(){
        this.cargarSeries();
    },
    methods:{
        cargarSeries(){
        service.cargarSeries().then((result) => {
        this.series = result;
        console.log(result);
      });
        },

        insertarPersonaje(){
            this.personaje={
               idPersonaje:0,
               nombre: this.nombre,
               imagen: this.imagen,
               idSerie: this.serie 
            };
            service.insertarPersonaje(this.personaje).then((result) => {
            console.log(result);
            });
            this.$router.push('/serie/'+this.serie)
        }
    },
}
</script>

<style>

</style>
