// ANGULAR/practicaseries/src/app/components/personajes/personajes.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Params, Router } from '@angular/router';
import { Personaje } from 'src/app/Models/Personaje';
import { SerieService } from 'src/app/services/serie.service';

@Component({
  selector: 'app-personajes',
  templateUrl: './personajes.component.html',
  styleUrls: ['./personajes.component.css']
})
export class PersonajesComponent implements OnInit {
  public idSerie!:number
  public personajes!:Array<Personaje>

  constructor(private _router: Router,private _activeRoute: ActivatedRoute,private _service: SerieService) { }

  cargarPersonajesId(id:number):void{
    this._service.getPersonajesId(id).subscribe(response=>{
      this.personajes=response;
    })
  }

  redirect(id: number): void {
    this._router.navigate(["/detalles", id]);
  }

  ngOnInit(): void {
    this._activeRoute.params.subscribe((params: Params) => {
        this.idSerie = parseInt(params['idserie']);
        this.cargarPersonajesId(this.idSerie)
    });
  }

}

<div class="container" >
    <a class="btn btn-danger" [routerLink]="['/detalles/',idSerie]">Volver</a>
    <table class="table table-bordered" style="display: table;margin: 0 auto;width: 70%;">
        <thead>
            <tr>
                <th>Personaje</th>
                <th>Imagen</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let personaje of personajes">
                <td>{{personaje.nombre}}</td>
                <td><img src="{{personaje.imagen}}" style="width: 300px;height: 300px;"></td>
            </tr>
        </tbody>
    </table>
</div>

// VUE/seriesvue/src/components/Personajes.vue
<template>
  <div>
      <h1>Personajes</h1>
      <router-link class="btn btn-danger" :to="'/serie/' + this.id">Volver</router-link>
      <table class="table table-bordered">
          <thead>
              <tr>
                  <th>Personaje</th>
                  <th>Imagen</th>
              </tr>
          </thead>
          <tbody>
              <tr v-for="(personaje, index) in personajes" :key="index">
                  <td>{{personaje.nombre}}</td>
                  <td><img style="width:420px;height:300px" :src="personaje.imagen" alt="Card image cap" /></td>
              </tr>
          </tbody>
      </table>
  </div>
</template>

<script>
import SeriesService from "./../services/SeriesService";

const service = new SeriesService();
export default {
    name:"Personajes",
    mounted() {
    this.id = this.$route.params.idserie;
    this.cargarPersonajes();
    console.log(this.personajes)
  },
    data(){
        return{
            id:0,
            personajes:[]
        };
    },
    methods:{
    cargarPersonajes() {
      service.personajesSerie(this.id).then((result) => {
        this.personajes = result;
        console.log(result);
      });
    },
    },
}
</script>

<style>
</style>
